#define MAINPREFIX z
#define PREFIX gr7bow_fgwf
#define MOD_NAME "Freeman: Guerrilla Warfare Factions"
#define AUTHOR "WOJTEK885"

#define REQUIRED_VERSION 2.20
#define REQUIRED_CBA_VERSION {3,18,6}
#define REQUIRED_ACE_VERSION {3,21,0}

#include "script_version.hpp"

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCH.BUILD
#define VERSION_AR  MAJOR,MINOR,PATCH,BUILD

#ifndef COMPONENT_BEAUTIFIED
    #define COMPONENT_BEAUTIFIED COMPONENT
#endif
#ifdef SUBCOMPONENT
    #ifndef SUBCOMPONENT_BEAUTIFIED
        #define SUBCOMPONENT_BEAUTIFIED SUBCOMPONENT
    #endif
    #define COMPONENT_NAME QUOTE(MOD_NAME - COMPONENT_BEAUTIFIED (SUBCOMPONENT_BEAUTIFIED))
#else
    #define COMPONENT_NAME QUOTE(MOD_NAME - COMPONENT_BEAUTIFIED)
#endif
