name: HEMTT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - name: Run HEMTT check
        run: hemtt check --error-on-all --pedantic
