name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate config
        run: python tools/config_style_checker.py

      - name: Check for BOM
        uses: arma-actions/bom-check@master
        with:
          path: addons
